import { FocusSession, Project, Task } from '../types/todo';

export const DEFAULT_PROJECTS: Project[] = [
  { id: 'work', name: 'Work & Projects', color: '#4f46e5' }, // indigo
  { id: 'personal', name: 'Personal & Health', color: '#059669' }, // emerald
  { id: 'design', name: 'Design System', color: '#7c3aed' }, // violet
  { id: 'finance', name: 'Finance & Ops', color: '#d97706' }, // amber
];

export function getTodayDateString(offsetDays: number = 0): string {
  const d = new Date();
  if (offsetDays !== 0) {
    d.setDate(d.getDate() + offsetDays);
  }
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export function getPastDateIso(daysAgo: number, hoursAgo: number = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(d.getHours() - hoursAgo);
  return d.toISOString();
}

export const INITIAL_FOCUS_SESSIONS: FocusSession[] = [
  {
    id: 'fs-1',
    taskId: 'task-1',
    taskTitle: 'Finalize Q4 product roadmap & resource allocation',
    projectId: 'work',
    durationMinutes: 25,
    completedAt: getPastDateIso(0, 2),
    mode: 'pomodoro',
  },
  {
    id: 'fs-2',
    taskId: 'task-3',
    taskTitle: '30-minute high-cadence mobility & core stretch',
    projectId: 'personal',
    durationMinutes: 30,
    completedAt: getPastDateIso(0, 4),
    mode: 'pomodoro',
  },
  {
    id: 'fs-3',
    taskId: 'task-past-1',
    taskTitle: 'Refactor authentication middleware & tokens',
    projectId: 'work',
    durationMinutes: 45,
    completedAt: getPastDateIso(1, 3),
    mode: 'pomodoro',
  },
  {
    id: 'fs-4',
    taskId: 'task-past-1',
    taskTitle: 'Refactor authentication middleware & tokens',
    projectId: 'work',
    durationMinutes: 25,
    completedAt: getPastDateIso(1, 5),
    mode: 'pomodoro',
  },
  {
    id: 'fs-5',
    taskId: 'task-past-2',
    taskTitle: 'Prepare financial variance deck for executive review',
    projectId: 'finance',
    durationMinutes: 50,
    completedAt: getPastDateIso(2, 4),
    mode: 'pomodoro',
  },
  {
    id: 'fs-6',
    taskId: 'task-past-3',
    taskTitle: 'Design token hierarchy audit in Figma',
    projectId: 'design',
    durationMinutes: 35,
    completedAt: getPastDateIso(3, 2),
    mode: 'pomodoro',
  },
  {
    id: 'fs-7',
    taskId: 'task-past-4',
    taskTitle: 'Database indexing optimization for search latency',
    projectId: 'work',
    durationMinutes: 60,
    completedAt: getPastDateIso(4, 3),
    mode: 'pomodoro',
  },
  {
    id: 'fs-8',
    taskId: 'task-past-5',
    taskTitle: 'Weekly strategic review & OKR alignments',
    projectId: 'work',
    durationMinutes: 25,
    completedAt: getPastDateIso(5, 6),
    mode: 'pomodoro',
  },
  {
    id: 'fs-9',
    taskId: 'task-past-6',
    taskTitle: 'Run 5km interval tempo pace',
    projectId: 'personal',
    durationMinutes: 30,
    completedAt: getPastDateIso(6, 4),
    mode: 'pomodoro',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-past-1',
    title: 'Refactor authentication middleware & tokens',
    description: 'Migrate to unified JWT verification with automatic secret rotation and cookie-safe headers.',
    completed: true,
    completedAt: getPastDateIso(1, 3),
    createdAt: getPastDateIso(2, 8),
    dueDate: getTodayDateString(-1),
    priority: 'high',
    projectId: 'work',
    tags: ['backend', 'security'],
    subtasks: [
      { id: 'st-p1-1', title: 'Rotate expired secrets', completed: true },
      { id: 'st-p1-2', title: 'Verify session revocation', completed: true },
    ],
    estimatedMinutes: 50,
    focusMinutesSpent: 70,
    isPinned: false,
  },
  {
    id: 'task-past-2',
    title: 'Prepare financial variance deck for executive review',
    description: 'Consolidate AWS, GCP, and SaaS subscription operational variance for Q3.',
    completed: true,
    completedAt: getPastDateIso(2, 4),
    createdAt: getPastDateIso(3, 8),
    dueDate: getTodayDateString(-2),
    priority: 'urgent',
    projectId: 'finance',
    tags: ['budget', 'executive'],
    subtasks: [],
    estimatedMinutes: 60,
    focusMinutesSpent: 50,
    isPinned: false,
  },
  {
    id: 'task-past-3',
    title: 'Design token hierarchy audit in Figma',
    description: 'Ensure spacing, typography scales, and surface color palettes match design token specs.',
    completed: true,
    completedAt: getPastDateIso(3, 2),
    createdAt: getPastDateIso(4, 5),
    dueDate: getTodayDateString(-3),
    priority: 'medium',
    projectId: 'design',
    tags: ['design-system'],
    subtasks: [],
    estimatedMinutes: 40,
    focusMinutesSpent: 35,
    isPinned: false,
  },
  {
    id: 'task-past-4',
    title: 'Database indexing optimization for search latency',
    description: 'Add composite B-tree index on (account_id, created_at) to decrease p99 query latency.',
    completed: true,
    completedAt: getPastDateIso(4, 3),
    createdAt: getPastDateIso(5, 7),
    dueDate: getTodayDateString(-4),
    priority: 'urgent',
    projectId: 'work',
    tags: ['database', 'performance'],
    subtasks: [],
    estimatedMinutes: 60,
    focusMinutesSpent: 60,
    isPinned: false,
  },
  {
    id: 'task-past-5',
    title: 'Weekly strategic review & OKR alignments',
    description: 'Sync with lead developers and engineering heads on cross-team deliverables.',
    completed: true,
    completedAt: getPastDateIso(5, 6),
    createdAt: getPastDateIso(6, 4),
    dueDate: getTodayDateString(-5),
    priority: 'high',
    projectId: 'work',
    tags: ['management'],
    subtasks: [],
    estimatedMinutes: 30,
    focusMinutesSpent: 25,
    isPinned: false,
  },
  {
    id: 'task-past-6',
    title: 'Run 5km interval tempo pace',
    description: 'Cardio training session for endurance and energy reset.',
    completed: true,
    completedAt: getPastDateIso(6, 4),
    createdAt: getPastDateIso(7, 2),
    dueDate: getTodayDateString(-6),
    priority: 'low',
    projectId: 'personal',
    tags: ['health'],
    subtasks: [],
    estimatedMinutes: 35,
    focusMinutesSpent: 30,
    isPinned: false,
  },
  {
    id: 'task-1',
    title: 'Finalize Q4 product roadmap & resource allocation',
    description: 'Synthesize user feedback and coordinate engineering priorities for the upcoming milestone release.',
    completed: false,
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    dueDate: getTodayDateString(0),
    dueTime: '15:00',
    priority: 'urgent',
    projectId: 'work',
    tags: ['strategy', 'roadmap', 'core'],
    subtasks: [
      { id: 'st-1-1', title: 'Audit pending feature requests', completed: true },
      { id: 'st-1-2', title: 'Draft executive summary slide deck', completed: true },
      { id: 'st-1-3', title: 'Schedule sync with lead architects', completed: false },
    ],
    estimatedMinutes: 50,
    focusMinutesSpent: 25,
    isPinned: true,
  },
  {
    id: 'task-2',
    title: 'Audit contrast ratios & keyboard accessibility in checkout',
    description: 'Ensure all focus rings, screen reader landmarks, and contrast tokens adhere strictly to WCAG AA.',
    completed: false,
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    dueDate: getTodayDateString(0),
    dueTime: '17:30',
    priority: 'high',
    projectId: 'design',
    tags: ['accessibility', 'design-system'],
    subtasks: [
      { id: 'st-2-1', title: 'Test tab order through payment steps', completed: false },
      { id: 'st-2-2', title: 'Inspect dark mode text contrast on inputs', completed: false },
    ],
    estimatedMinutes: 45,
    focusMinutesSpent: 0,
    isPinned: false,
  },
  {
    id: 'task-3',
    title: '30-minute high-cadence mobility & core stretch',
    description: 'Daily midday wellness session to prevent desk fatigue and reset postural focus.',
    completed: true,
    completedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    dueDate: getTodayDateString(0),
    dueTime: '12:00',
    priority: 'low',
    projectId: 'personal',
    tags: ['health', 'routine'],
    subtasks: [
      { id: 'st-3-1', title: 'Hamstring & spine mobility sequence', completed: true },
      { id: 'st-3-2', title: 'Hydrate 750ml water', completed: true },
    ],
    estimatedMinutes: 30,
    focusMinutesSpent: 30,
    isPinned: false,
  },
  {
    id: 'task-4',
    title: 'Review quarterly vendor subscriptions and SaaS spend',
    description: 'Identify unused development licenses and negotiate annual renewal terms.',
    completed: false,
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    dueDate: getTodayDateString(1),
    dueTime: '14:00',
    priority: 'medium',
    projectId: 'finance',
    tags: ['budget', 'audit'],
    subtasks: [
      { id: 'st-4-1', title: 'Export seat utilization sheet', completed: true },
      { id: 'st-4-2', title: 'Flag stale seats (>60 days inactive)', completed: false },
    ],
    estimatedMinutes: 40,
    focusMinutesSpent: 0,
    isPinned: false,
  },
  {
    id: 'task-5',
    title: 'Deep dive into distributed systems chapter 4 (Replication)',
    description: 'Study leaderless consensus algorithms and write concise implementation takeaways in knowledge base.',
    completed: false,
    createdAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    dueDate: getTodayDateString(2),
    priority: 'low',
    projectId: 'personal',
    tags: ['reading', 'architecture'],
    subtasks: [],
    estimatedMinutes: 60,
    focusMinutesSpent: 0,
    isPinned: false,
  },
];
